### PR TITLE
Fix varchar length in createDF

### PR DESCRIPTION
**Pull request by kyokonishito**
I fixed a logic for counting varchar length in createDF.

Current logic is only for single byte characters. If the data is multibyte  characters like Japanese, the varchar length with current logic is not correct, it is very short.

I fixed to counting byte length with utf-8 string as varchar length.

### CODE REVIEW

**Comment by kyokonishito** [comment]
@baklarz Is it possible for you to merge this pull request? If you have any questions, please let me know. Thanks.

**Comment by baklarz** [comment]
Actually, I have a number of updates regarding UTF-8 characters etc... We had to analyze some data that included Unicode 2+ byte characters and ended up creating an extension to the creation command:
USING df CREATE TABLE .... NCHAR x or PADDING x and CHARTYPE x

NCHAR x / PADDING x would take the size of the character string returned by Pandas and "Pad" or expand the size of the VARCHAR that we generate by this amount. So if Pandas tells the program the field is 10 characters wide, a PADDING of 2 would generate VARCHAR(20) instead of VARCHAR(10). You could also use fractions so that NCHAR 1.5 would result in VARCHAR(10) becoming VARCHAR(15). 

Alternatively, you can also use the CHARTYPE x option to change the default character format from VARCHAR to whatever you want. So you could say CHARTYPE NCHAR or CHARTYPE VARGRAPHIC which would result in the program generating VARGRAPHIC(10) (without padding) or NCHAR 1.5 CHARTYPE VARGRAPHIC resulting in VARGRAPHIC(15).

I haven't uploaded this code yet but will do so shortly. You have any additional suggestions on how to handle these Unicode character sets?

The other options we were adding include INTTYPE, FLOATTYPE, CHARTYPE, CLOBTYPE, BLOBTYPE, ... so that you can specify exactly how you want the Pandas columns to be represented in Db2. Pandas causes a number of issues when trying to determine the "real" format of a column so sometimes you have to just create the table using the CREATE command (without data), modify the table definition and then use the refresh option to load the data into the table.

**Comment by kyokonishito** [comment]
@baklarz Thank you for your detail comments. I understand you have a plan to fix. 
My colleague had a hands-on workshop today.  He used my fixed version today because there are issues for creating table from DataFrame if it has Japanese characters. We have an alternative module db2.ipynb in my branch, so we can wait your official fix.

**Comment by baklarz** [comment]
FYI - I did update the code with your UTF suggestion. Thanks for that! I've updated the code with additional options for changing the data types that are used for columns and an additional PADDING function in case the UTF length is insufficient for the column.

**Pull request closed without merging**
